@HomeLibrary.Api_HostAddress = http://localhost:5163

### Import CSV

POST {{HomeLibrary.Api_HostAddress}}/api/imports

###

### Get Books

GET {{HomeLibrary.Api_HostAddress}}/api/books
Accept: application/json